import type { Place } from '../types';

export const CHENNAI_PLACES: Place[] = [
  {
    id: 'chn-marina-1',
    name: 'Marina Beach & Light House',
    category: 'viewpoints',
    description: 'The second longest natural urban beach in the world stretching 13 km along the Bay of Bengal. Famous for evening sea breeze, fresh sundal and crispy fish fry stalls, horse rides, and panoramic views from the Chennai Light House deck.',
    address: 'Kamarajar Promenade, Marina Beach',
    area: 'Marina Beach',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0500,
    longitude: 80.2824,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.8,
    reviewCount: 48000,
    openingTime: '05:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Public Beach Access', '₹20 Light House Elevator Ticket', 'Iconic Sundal & Bajjis under ₹40'],
    distanceKm: 3.2
  },
  {
    id: 'chn-besant-1',
    name: 'Besant Nagar / Edward Elliot\'s Beach (Bessie)',
    category: 'cafes',
    description: 'The undisputed favorite hangout for Chennai college students. Clean sandy shoreline, the historic Karl Schmidt Memorial, vibrant beachside cafes like Cozee and Murugan Idli, and chilled night breezes.',
    address: '6th Avenue, Besant Nagar',
    area: 'Besant Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0002,
    longitude: 80.2713,
    priceLevel: 1,
    approxCostForOne: 120,
    rating: 4.9,
    reviewCount: 39500,
    openingTime: '00:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Safe & Well-lit Night Hangout', 'Street Food & Gelato Shacks', 'Scenic Morning Jogging Track'],
    distanceKm: 6.8
  },
  {
    id: 'chn-kapaleeshwarar-1',
    name: 'Kapaleeshwarar Temple & Mylapore Tank',
    category: 'cultural_temples',
    description: '7th-century Dravidian architectural masterpiece dedicated to Lord Shiva and Goddess Karpagambal. Features a 120-ft rainbow-colored Gopuram, historic temple tank, ancient inscriptions, and vibrant Carnatic music atmosphere.',
    address: '12 North Mada Street, Mylapore',
    area: 'Mylapore',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0336,
    longitude: 80.2694,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.9,
    reviewCount: 42000,
    openingTime: '05:30',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Historic Agraharam Street Walk', 'Legendary Mami Tiffin Nearby'],
    distanceKm: 4.5
  },
  {
    id: 'chn-parthasarathy-1',
    name: 'Sri Parthasarathy Swamy Temple, Triplicane',
    category: 'cultural_temples',
    description: 'One of the oldest surviving structures in Chennai built by the Pallavas in the 8th century. Dedicated to Lord Krishna as Arjuna\'s charioteer, displaying 5 avatars of Vishnu and intricate Vijayanagara mandapas.',
    address: 'Car Street, Triplicane',
    area: 'Triplicane',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0538,
    longitude: 80.2773,
    priceLevel: 0,
    approxCostForOne: 25,
    rating: 4.8,
    reviewCount: 28000,
    openingTime: '06:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Temple Entry', 'Famous Sakkarai Pongal & Puliyodarai', 'Historic Triplicane Street Food'],
    distanceKm: 3.8
  },
  {
    id: 'chn-santhome-1',
    name: 'San Thome Cathedral Basilica',
    category: 'cultural_temples',
    description: 'Stunning 16th-century Neo-Gothic Catholic cathedral built over the tomb of St. Thomas, one of the twelve apostles of Jesus. Snow-white spires, museum with 1st-century relics, and peaceful beachside courtyard.',
    address: '38 San Thome High Road, Mylapore',
    area: 'San Thome',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0335,
    longitude: 80.2785,
    priceLevel: 0,
    approxCostForOne: 20,
    rating: 4.8,
    reviewCount: 24500,
    openingTime: '06:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Free Entry to Cathedral & Crypt', 'Historical Relics Museum', 'Direct Access to Marina Coast'],
    distanceKm: 4.8
  },
  {
    id: 'chn-fort-1',
    name: 'Fort St. George & Clive House Museum',
    category: 'cultural_temples',
    description: 'The first English fortress constructed in India (1644) by the British East India Company. Houses the oldest Anglican church in the East (St. Mary\'s Church), military cannons, colonial portrait gallery, and historical weaponry.',
    address: 'Rajaji Salai, Fort St George',
    area: 'George Town',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0797,
    longitude: 80.2874,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.6,
    reviewCount: 16800,
    openingTime: '09:00',
    closingTime: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹25 Student/Indian Entry Ticket', 'Archaeological Museum', 'Oldest Flagstaff in India'],
    distanceKm: 2.5
  },
  {
    id: 'chn-museum-1',
    name: 'Government Museum & National Art Gallery, Egmore',
    category: 'study_spots',
    description: 'Established in 1851, it is the second oldest museum in India. Spans six independent heritage buildings housing world-famous Chola bronzes, Roman antiquities, Amaravati Buddhist sculptures, and the Connemara Public Library.',
    address: 'Pantheon Road, Egmore',
    area: 'Egmore',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0699,
    longitude: 80.2568,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.7,
    reviewCount: 22000,
    openingTime: '09:30',
    closingTime: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['₹20 Indian Student Ticket', 'Vast Historical Reference Galleries', 'Quiet Green Lawn Study Spots'],
    distanceKm: 3.1
  },
  {
    id: 'chn-guindy-1',
    name: 'Guindy National Park & Snake Park',
    category: 'parks_nature',
    description: 'One of the few national parks situated inside a metropolis. Home to spotted deer, endangered blackbucks, over 150 bird species, lush tropical dry evergreen scrub forest, and the famous Madras Snake Park.',
    address: 'Rangeguindy, Guindy',
    area: 'Guindy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0067,
    longitude: 80.2206,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.6,
    reviewCount: 19800,
    openingTime: '09:00',
    closingTime: '17:30',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹20 Student Entry Fee', 'Deer Spotting in the Heart of City', 'IIT Madras Bordered Green Canopy'],
    distanceKm: 8.2
  },
  {
    id: 'chn-semmozhi-1',
    name: 'Semmozhi Poonga Botanical Garden',
    category: 'parks_nature',
    description: 'A 20-acre lush botanical oasis situated in the heart of Chennai on Cathedral Road. Features 22 thematic gardens, rare medicinal herbs, vertical green walls, bonsai pavilion, and quiet bench avenues for group reading.',
    address: 'Cathedral Road, Teynampet',
    area: 'Cathedral Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0487,
    longitude: 80.2505,
    priceLevel: 0,
    approxCostForOne: 25,
    rating: 4.6,
    reviewCount: 18400,
    openingTime: '06:00',
    closingTime: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹15 Entry Ticket', 'Peaceful Shaded Study Zones', 'Metro Accessible via AG-DMS'],
    distanceKm: 4.1
  },
  {
    id: 'chn-vandalur-1',
    name: 'Arignar Anna Zoological Park (Vandalur Zoo)',
    category: 'parks_nature',
    description: 'India\'s largest zoological garden spanning 1,490 acres. Features white tigers, lion and deer safaris, vast elephant corridors, cycling tracks under tree canopies, and nocturnal animal houses.',
    address: 'GST Road, Vandalur',
    area: 'Vandalur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.8797,
    longitude: 80.0818,
    priceLevel: 1,
    approxCostForOne: 90,
    rating: 4.7,
    reviewCount: 36000,
    openingTime: '09:00',
    closingTime: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Student Group Discount on ID', 'Bicycle Rentals inside park ₹50', 'Full Day Nature Adventure'],
    distanceKm: 26.0
  },
  {
    id: 'chn-dakshina-1',
    name: 'DakshinaChitra Heritage Village, ECR',
    category: 'cultural_temples',
    description: 'An acclaimed cross-cultural living history museum showcasing traditional architecture, craft, folk arts, and lifestyles of Tamil Nadu, Kerala, Karnataka, and Andhra Pradesh through 18 restored heritage houses.',
    address: 'East Coast Road, Muttukadu',
    area: 'ECR Muttukadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.8223,
    longitude: 80.2422,
    priceLevel: 1,
    approxCostForOne: 120,
    rating: 4.8,
    reviewCount: 15400,
    openingTime: '10:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹75 Student Concession Ticket', 'Pottery & Palm Leaf Workshops', 'Scenic ECR Highway Drive'],
    distanceKm: 21.5
  },
  {
    id: 'chn-food-mylapore-1',
    name: 'Mylapore Cultural Food Trail (Rayar\'s & Mami Mess)',
    category: 'street_food',
    description: 'The golden culinary route of South Chennai. Relish piping hot ghee pongal, crispy Mysore bajjis with coconut chutney at Rayar\'s Mess, and legendary tumbler filter coffee from century-old agraharam stalls.',
    address: 'Arundale Street & Pitchu Pillai St, Mylapore',
    area: 'Mylapore',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0331,
    longitude: 80.2680,
    priceLevel: 1,
    approxCostForOne: 60,
    rating: 4.9,
    reviewCount: 29000,
    openingTime: '06:30',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Full Authentic Breakfast Under ₹60', 'Original Filter Kaapi ₹20', 'Iconic Historic College Vibe'],
    distanceKm: 4.4
  },
  {
    id: 'chn-food-sowcarpet-1',
    name: 'Sowcarpet Street Food Hub (Mint Street)',
    category: 'street_food',
    description: 'Chennai\'s bustling North Indian food paradise in George Town! Famous for the legendary Murukku Cheese Sandwich, onion kachoris at Maya Chaat, chilled badam milk at Kakada Ramprasad, and piping hot jalebis.',
    address: 'Mint Street & NSC Bose Road, Sowcarpet',
    area: 'Sowcarpet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0970,
    longitude: 80.2778,
    priceLevel: 1,
    approxCostForOne: 90,
    rating: 4.8,
    reviewCount: 26500,
    openingTime: '11:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Murukku Sandwich ₹60', 'Badam Milk & Gulab Jamun ₹40', 'Group Food Crawl Hotspot'],
    distanceKm: 2.8
  },
  {
    id: 'chn-covelong-1',
    name: 'Covelong (Kovalam) Beach & Surf Point',
    category: 'weekend_trips',
    description: 'A charming fishing village transformed into South India\'s top surf hub. Clean sandy beaches, surf schools with beginner lessons, beach volleyball, ocean kayak tours, and relaxed coastal cafes.',
    address: 'Kovalam Beach Road, ECR',
    area: 'Kovalam / Covelong',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.7937,
    longitude: 80.2520,
    priceLevel: 1,
    approxCostForOne: 180,
    rating: 4.8,
    reviewCount: 18900,
    openingTime: '06:00',
    closingTime: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Group Surf Lesson Discounts', 'Sunset Coastal Bike Rides', 'Less Crowded than Marina'],
    distanceKm: 28.0
  },
  {
    id: 'chn-mahabalipuram-1',
    name: 'Mahabalipuram Shore Temple & Pancha Rathas',
    category: 'cultural_temples',
    description: 'UNESCO World Heritage 7th and 8th century monolithic rock temples overlooking the roaring waves of Bay of Bengal. Features the descent of the Ganges stone relief, Krishna\'s Butterball, and beach seafood shacks.',
    address: 'Beach Road, Mahabalipuram',
    area: 'Mahabalipuram (Chennai Outskirts)',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.6169,
    longitude: 80.1927,
    priceLevel: 1,
    approxCostForOne: 90,
    rating: 4.9,
    reviewCount: 52000,
    openingTime: '06:00',
    closingTime: '18:30',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹40 Indian Student Entry', 'Krishna\'s Butterball Photo Walk', 'Budget ECR Bus from CMBT ₹45'],
    distanceKm: 48.0
  },
  {
    id: 'chn-express-mall-1',
    name: 'Express Avenue Mall & Escape Cinemas',
    category: 'entertainment',
    description: 'Central Chennai\'s buzzing shopping and movie destination in Royapettah. Houses Escape Cinemas with luxury recliners and student ticket rates, massive gaming zone, bowling alleys, and huge food court.',
    address: 'Whites Road, Royapettah',
    area: 'Royapettah',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0587,
    longitude: 80.2641,
    priceLevel: 2,
    approxCostForOne: 250,
    rating: 4.7,
    reviewCount: 38000,
    openingTime: '10:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Student Matinee Tickets Under ₹150', 'Gaming Arcade & Bowling', 'Air-Conditioned Study Lounges'],
    distanceKm: 3.6
  },
  {
    id: 'chn-phoenix-1',
    name: 'Phoenix Marketcity & VR Chennai',
    category: 'shopping',
    description: 'Mega lifestyle and hangout hubs featuring IMAX, gaming arcades, craft beer spots, international brand stores, and open courtyards hosting college band concerts and cultural festivals.',
    address: 'Velachery Main Road & Anna Nagar',
    area: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.9922,
    longitude: 80.2170,
    priceLevel: 2,
    approxCostForOne: 280,
    rating: 4.8,
    reviewCount: 41000,
    openingTime: '10:30',
    closingTime: '22:30',
    imageUrl: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['College Discounts on Bowling', 'Huge Budget Food Court', 'Weekend Live Concerts'],
    distanceKm: 9.5
  },
  {
    id: 'chn-amethyst-1',
    name: 'Amethyst Cafe & Wild Garden',
    category: 'cafes',
    description: 'A restored colonial mansion nestled amidst tropical trees, verandah armchairs, and antique book racks. Perfect for college groups working on projects, aesthetic Instagram photos, and artisanal iced coffees.',
    address: 'Whites Road, Royapettah',
    area: 'Royapettah',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0544,
    longitude: 80.2604,
    priceLevel: 2,
    approxCostForOne: 240,
    rating: 4.7,
    reviewCount: 14200,
    openingTime: '10:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Fast Wi-Fi & Work Verandas', 'Lush Garden Photo Ambience', 'Special Cold Brews'],
    distanceKm: 3.9
  },
  {
    id: 'chn-writers-cafe-1',
    name: 'Writer\'s Cafe & Higginbothams Books',
    category: 'study_spots',
    description: 'A Swiss pastry and book cafe run in association with NGOs supporting burn survivors. Features floor-to-ceiling bookshelves from Higginbothams, artisanal pizzas, tranquil study alcoves, and power points.',
    address: '98 Peter\'s Road, Gopalapuram',
    area: 'Gopalapuram',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0489,
    longitude: 80.2558,
    priceLevel: 1,
    approxCostForOne: 180,
    rating: 4.8,
    reviewCount: 12500,
    openingTime: '09:30',
    closingTime: '22:30',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Free Books to Read While Dining', 'Fast Charging Points at Every Table', 'Social Cause Partnership'],
    distanceKm: 4.3
  },
  {
    id: 'chn-theosophical-1',
    name: 'Theosophical Society & 450-Year-Old Banyan Tree',
    category: 'parks_nature',
    description: 'A tranquil 260-acre green canopy along the Adyar river estuary. Home to one of the world\'s largest banyan trees (covering 40,000 sq ft), migratory birds, serene bamboo forests, and ancient Buddhist reflection shrines.',
    address: 'Adyar River Bank, Adyar',
    area: 'Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0097,
    longitude: 80.2600,
    priceLevel: 0,
    approxCostForOne: 20,
    rating: 4.8,
    reviewCount: 16500,
    openingTime: '08:30',
    closingTime: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free Entry', 'Gigantic 450-Year Historic Banyan Tree', 'Ultimate Quiet Sanctuary in City'],
    distanceKm: 7.1
  },
  {
    id: 'chn-ashtalakshmi-1',
    name: 'Ashtalakshmi Temple, Besant Nagar',
    category: 'cultural_temples',
    description: 'A rare multi-tiered coastal temple on the Elliot\'s beach promenade dedicated to the eight manifestations of Goddess Lakshmi. Climb stone stairways overlooking crashing Bay of Bengal waves.',
    address: 'Elliot\'s Beach Road, Besant Nagar',
    area: 'Besant Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.9942,
    longitude: 80.2725,
    priceLevel: 0,
    approxCostForOne: 25,
    rating: 4.8,
    reviewCount: 21000,
    openingTime: '06:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Stunning Ocean View from Top Tier', 'Direct Beachfront Walkway'],
    distanceKm: 7.2
  },
  {
    id: 'chn-birla-1',
    name: 'Birla Planetarium & Periyar Science Centre',
    category: 'entertainment',
    description: 'South India\'s most versatile planetarium equipped with 360-degree digital cosmic projection, defense science parks, evolution park with life-size animatronic dinosaurs, and science labs.',
    address: 'Gandhi Mandapam Road, Kotturpuram',
    area: 'Kotturpuram',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0116,
    longitude: 80.2444,
    priceLevel: 0,
    approxCostForOne: 45,
    rating: 4.6,
    reviewCount: 15800,
    openingTime: '10:00',
    closingTime: '17:45',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹30 Student Sky Show Ticket', 'Science & Innovation Exhibits', 'Close to Anna University'],
    distanceKm: 7.5
  },
  {
    id: 'chn-thiruvanmiyur-1',
    name: 'Thiruvanmiyur Beach & Seaside Boardwalk',
    category: 'viewpoints',
    description: 'A quieter, uncommercialized ocean beach situated between Adyar and Kottivakkam. Clean sand, crashing surf, peaceful morning sunrise yoga spots, and street carts serving fresh tender coconut.',
    address: 'Thiruvanmiyur Beach Road',
    area: 'Thiruvanmiyur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.9808,
    longitude: 80.2644,
    priceLevel: 0,
    approxCostForOne: 35,
    rating: 4.7,
    reviewCount: 19500,
    openingTime: '05:00',
    closingTime: '22:30',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Public Beach', 'Pristine Sunrise Photography', 'Uncrowded Seaside Stroll'],
    distanceKm: 8.8
  },
  {
    id: 'chn-crocbank-1',
    name: 'Madras Crocodile Bank Trust, ECR',
    category: 'parks_nature',
    description: 'One of the world\'s largest reptile zoos and research sanctuaries. Home to over 2,400 crocodiles, giant Aldabra tortoises, venomous snake milking center, and guided night herpetology safaris.',
    address: 'Post Bag No 4, Mahabalipuram Road, Vadanemmeli',
    area: 'ECR Vadanemmeli',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.7663,
    longitude: 80.2372,
    priceLevel: 1,
    approxCostForOne: 80,
    rating: 4.7,
    reviewCount: 18200,
    openingTime: '09:00',
    closingTime: '17:30',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹60 Student Concession', 'Snake Venom Extraction Demos', 'Interactive Underwater Feeding View'],
    distanceKm: 34.0
  },
  {
    id: 'chn-chetpet-1',
    name: 'Chetpet EcoPark & Angling Lake',
    category: 'parks_nature',
    description: 'A 16-acre freshwater lake and eco-park in central Chennai. Offers pedal boating, certified recreational sport fishing, children\'s science park, and paved jogging track surrounded by water lilies.',
    address: '814 EVR Periyar Salai, Chetpet',
    area: 'Chetpet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0722,
    longitude: 80.2415,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.6,
    reviewCount: 12300,
    openingTime: '06:00',
    closingTime: '19:30',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹25 Walkers Entry', '₹50 Pedal Boating', 'Adjacent to Chetpet Railway Station'],
    distanceKm: 4.2
  },
  {
    id: 'chn-vadapalani-1',
    name: 'Vadapalani Andavar Murugan Temple',
    category: 'cultural_temples',
    description: 'Renowned 19th-century temple dedicated to Lord Murugan with an imposing multi-tiered golden gopuram, intricate stucco sculptures, and bustling traditional brass bazaars.',
    address: 'Palani Andavar Koil St, Vadapalani',
    area: 'Vadapalani',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0537,
    longitude: 80.2114,
    priceLevel: 0,
    approxCostForOne: 25,
    rating: 4.8,
    reviewCount: 31000,
    openingTime: '05:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Vibrant Festive Atmosphere', 'Direct Metro Connectivity at Vadapalani'],
    distanceKm: 6.9
  },
  {
    id: 'chn-ciclo-1',
    name: 'Ciclo Cafe & Bakery, Kotturpuram',
    category: 'cafes',
    description: 'India\'s first cycle-themed cafe featuring vintage bicycle wall art, chandeliers made of bicycle wheels, artisan sourdough pizzas, gourmet sandwiches, and chocolate shakes.',
    address: 'Old No 33 New No 47 Gandhi Mandapam Rd, Kotturpuram',
    area: 'Kotturpuram',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0186,
    longitude: 80.2407,
    priceLevel: 2,
    approxCostForOne: 220,
    rating: 4.7,
    reviewCount: 11500,
    openingTime: '11:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Wi-Fi & Cycling Merchandise', 'Great Student Group Hangout', 'Signature Woodfire Pizzas'],
    distanceKm: 7.2
  },
  {
    id: 'chn-kalakshetra-1',
    name: 'Kalakshetra Foundation & Craft Center',
    category: 'cultural_temples',
    description: 'World-renowned arts and cultural academy founded by Rukmini Devi Arundale. 100-acre green sanctuary devoted to classical Bharatanatyam, Carnatic music, handloom saree weaving, and kalamkari art.',
    address: 'Kalakshetra Road, Thiruvanmiyur',
    area: 'Thiruvanmiyur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.9866,
    longitude: 80.2612,
    priceLevel: 1,
    approxCostForOne: 80,
    rating: 4.9,
    reviewCount: 13200,
    openingTime: '08:30',
    closingTime: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Student Campus Heritage Tour', 'Live Classical Dance Rehearsals', 'Traditional Handloom Weaving Center'],
    distanceKm: 8.5
  }
];
