import type { CategoryInfo, Place } from '../types';
import { PAN_INDIA_PLACES, ALL_INDIAN_STATES_UTS } from './indiaDestinations';

export { ALL_INDIAN_STATES_UTS, PAN_INDIA_PLACES };

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'cafes',
    name: 'Cafés & Hangouts',
    emoji: '☕',
    description: 'Aesthetic, budget-friendly coffee spots with Wi-Fi & student vibes.',
    tagline: 'From ₹90',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  },
  {
    id: 'study_spots',
    name: 'Study & Work Spots',
    emoji: '📚',
    description: 'Quiet bookstores, reading rooms, and spots with fast Wi-Fi and charging points.',
    tagline: 'Quiet & Wi-Fi',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  },
  {
    id: 'street_food',
    name: 'Street Food Hubs',
    emoji: '🍕',
    description: 'Crispy dosas, chaats, rolls, and shawarmas that won\'t break your pocket.',
    tagline: 'Under ₹150',
    badgeColor: 'bg-red-500/20 text-red-300 border-red-500/30',
  },
  {
    id: 'theatres',
    name: 'Theatres & Stage',
    emoji: '🎬',
    description: 'Student discount movie halls, cultural stage plays, and indie film spots.',
    tagline: 'Tickets < ₹250',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  },
  {
    id: 'parks_nature',
    name: 'Parks & Nature',
    emoji: '🌳',
    description: 'Lush green escapes, shaded canopies, and chill lawn spaces for friends.',
    tagline: 'Free Entry',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'restaurants',
    name: 'Budget Restaurants',
    emoji: '🍔',
    description: 'Biryani hubs, South Indian tiffin meals, and group thali joints.',
    tagline: 'Group Friendly',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
  },
  {
    id: 'entertainment',
    name: 'Gaming & Fun Zones',
    emoji: '🎮',
    description: 'Bowling alleys, laser tag, retro arcade zones, and escape rooms.',
    tagline: 'Fun with Friends',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
  },
  {
    id: 'viewpoints',
    name: 'Sunset & Viewpoints',
    emoji: '🌅',
    description: 'Scenic hilltops, rooftop vistas, and lakeside twilight promenades.',
    tagline: 'Scenic Chill',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
  },
  {
    id: 'cultural_temples',
    name: 'Temples & Heritage',
    emoji: '🛕',
    description: 'Ancient architecture, peaceful courtyards, and iconic city landmarks.',
    tagline: 'Culture & Calm',
    badgeColor: 'bg-amber-600/20 text-amber-200 border-amber-600/30',
  },
  {
    id: 'shopping',
    name: 'Budget Bazaars & Flea',
    emoji: '🛍️',
    description: 'Thrift markets, street fashion avenues, and budget gadget havens.',
    tagline: 'Thrift & Bargains',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
  },
  {
    id: 'photo_spots',
    name: 'Instagram & Photo Spots',
    emoji: '📸',
    description: 'Graffiti walls, neon alleys, vintage heritage doorways, and golden hour spots.',
    tagline: 'Aesthetic Shots',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'weekend_trips',
    name: 'Weekend Getaways',
    emoji: '🔥',
    description: 'Day-trip treks, reservoir camp spots, and quick overnight bus adventures.',
    tagline: 'Under ₹800',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
  },
];

const BASE_PLACES: Place[] = [
  // ── STUDY SPOTS ──────────────────────────────────────────────────────
  {
    id: 'p-1',
    name: 'Blossom Book House & Reading Nook',
    category: 'study_spots',
    description: 'Legendary 3-storey bookstore on Church Street with quiet reading nooks and budget filter coffee next door.',
    address: '84, Church Street, Shanthala Nagar',
    area: 'Church Street',
    city: 'Bengaluru',
    latitude: 12.9749,
    longitude: 77.6082,
    priceLevel: 1,
    approxCostForOne: 80,
    rating: 4.8,
    reviewCount: 4920,
    openingTime: '10:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['50% Off Second-hand Books', 'Free Wi-Fi Zone'],
    distanceKm: 1.2,
  },
  {
    id: 'p-13',
    name: 'Koshy\'s Café – The Heritage Haunt',
    category: 'study_spots',
    description: 'A Bengaluru institution since 1940. Iconic wooden interiors, strong filter coffee, and the perfect quiet corner to journal or code.',
    address: '39, St. Marks Road',
    area: 'St. Marks Road',
    city: 'Bengaluru',
    latitude: 12.9721,
    longitude: 77.6024,
    priceLevel: 1,
    approxCostForOne: 180,
    rating: 4.6,
    reviewCount: 3200,
    openingTime: '09:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Student Writer Community Nights', 'Legendary ₹60 Filter Coffee'],
    distanceKm: 0.9,
  },
  // ── THEATRES ──────────────────────────────────────────────────────────
  {
    id: 'p-2',
    name: 'Ranga Shankara Theatre & Cafe',
    category: 'theatres',
    description: 'Iconic performing arts theatre with famous hot sabudana vadas and student discount stage productions.',
    address: '36/2 8th Cross Road, JP Nagar 2nd Phase',
    area: 'JP Nagar',
    city: 'Bengaluru',
    latitude: 12.9126,
    longitude: 77.5843,
    priceLevel: 1,
    approxCostForOne: 120,
    rating: 4.7,
    reviewCount: 1840,
    openingTime: '10:00',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹50 Sabudana Vada', '₹150 Student Play Passes'],
    distanceKm: 2.4,
  },
  {
    id: 'p-14',
    name: 'PVR Orion Mall – Midnight Screenings',
    category: 'theatres',
    description: 'Modern multiplex with an IMAX screen, midnight shows on weekends, and student ID discounts on weekday mornings.',
    address: 'Orion Mall, Rajajinagar',
    area: 'Rajajinagar',
    city: 'Bengaluru',
    latitude: 12.9979,
    longitude: 77.5517,
    priceLevel: 2,
    approxCostForOne: 220,
    rating: 4.4,
    reviewCount: 5600,
    openingTime: '09:00',
    closingTime: '01:00',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Morning shows ₹140', 'Student Card 20% Off', 'Midnight Friday shows'],
    distanceKm: 5.1,
  },
  // ── PARKS ──────────────────────────────────────────────────────────────
  {
    id: 'p-3',
    name: 'Cubbon Park Bamboo Grove & Lawns',
    category: 'parks_nature',
    description: 'A 300-acre lush green paradise with heritage red buildings, shaded cycle paths, and picnic lawns.',
    address: 'Kasturba Road, Sampangi Rama Nagara',
    area: 'Central District',
    city: 'Bengaluru',
    latitude: 12.9763,
    longitude: 77.5929,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.9,
    reviewCount: 8200,
    openingTime: '06:00',
    closingTime: '19:00',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free Entry', 'Picnic & Frisbee Allowed'],
    distanceKm: 1.8,
  },
  {
    id: 'p-15',
    name: 'Ulsoor Lake Promenade & Boating',
    category: 'parks_nature',
    description: 'A serene lake in the heart of the city with boating for ₹30, sunrise jogs, and migratory birds in winter.',
    address: 'Ulsoor Lake Rd, Halasuru',
    area: 'Halasuru',
    city: 'Bengaluru',
    latitude: 12.9837,
    longitude: 77.6179,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.5,
    reviewCount: 4100,
    openingTime: '06:00',
    closingTime: '18:30',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹30 Pedal Boating', 'Free Lakeside Walk'],
    distanceKm: 3.2,
  },
  // ── STREET FOOD ───────────────────────────────────────────────────────
  {
    id: 'p-4',
    name: 'VV Puram Food Street (Thindi Beedi)',
    category: 'street_food',
    description: 'Famous food street with over 20 stalls serving hot congress kadlekai, butter masala dosas, and rabdi kulfi.',
    address: 'Old Hospital Road, Sajjan Rao Circle, VV Puram',
    area: 'VV Puram',
    city: 'Bengaluru',
    latitude: 12.9515,
    longitude: 77.5768,
    priceLevel: 1,
    approxCostForOne: 150,
    rating: 4.6,
    reviewCount: 6150,
    openingTime: '17:30',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹40 Butter Dosa', 'Open Till Midnight'],
    distanceKm: 3.1,
  },
  {
    id: 'p-16',
    name: 'Shivaji Military Hotel – Thali Legends',
    category: 'street_food',
    description: 'No-frills, no-nonsense military-style canteen serving unlimited rice, sambar, rasam and 2 curries for ₹80.',
    address: '7, Mysore Bank Circle, Chamarajpet',
    area: 'Chamarajpet',
    city: 'Bengaluru',
    latitude: 12.9601,
    longitude: 77.5645,
    priceLevel: 1,
    approxCostForOne: 80,
    rating: 4.5,
    reviewCount: 7800,
    openingTime: '07:00',
    closingTime: '15:00',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['₹80 Full Thali Unlimited', 'Morning Idli at ₹20'],
    distanceKm: 4.0,
  },
  // ── CAFES ──────────────────────────────────────────────────────────────
  {
    id: 'p-5',
    name: 'Airlines Open-Air Banyan Tree Cafe',
    category: 'cafes',
    description: 'Open-air drive-in cafe under a gigantic banyan tree serving steaming South Indian filter coffee and crispy vadas.',
    address: '4, State Bank of India Rd, Shanthala Nagar',
    area: 'Ashok Nagar',
    city: 'Bengaluru',
    latitude: 12.9723,
    longitude: 77.5968,
    priceLevel: 1,
    approxCostForOne: 140,
    rating: 4.5,
    reviewCount: 3890,
    openingTime: '07:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Legendary ₹35 Filter Coffee', 'Youth Hangout'],
    distanceKm: 1.5,
  },
  {
    id: 'p-17',
    name: 'Cafe Matteo – Work & Chill',
    category: 'cafes',
    description: 'Modern Bangalorean café with fast Wi-Fi, USB charging at every table, and student-friendly work packages.',
    address: 'UB City Mall, Vittal Mallya Road',
    area: 'CBD',
    city: 'Bengaluru',
    latitude: 12.9717,
    longitude: 77.5967,
    priceLevel: 2,
    approxCostForOne: 280,
    rating: 4.4,
    reviewCount: 2100,
    openingTime: '09:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Student Work Package ₹199 (coffee+Wi-Fi)', '4-hour Seat Guarantee'],
    distanceKm: 1.3,
  },
  // ── ENTERTAINMENT ─────────────────────────────────────────────────────
  {
    id: 'p-6',
    name: 'Amoeba Bowling & Arcade Arena',
    category: 'entertainment',
    description: 'High-energy 12-lane bowling alley with arcade machines, air hockey, and student happy hour rates.',
    address: 'Church Street, Shanthala Nagar',
    area: 'Church Street',
    city: 'Bengaluru',
    latitude: 12.9752,
    longitude: 77.6065,
    priceLevel: 2,
    approxCostForOne: 250,
    rating: 4.4,
    reviewCount: 2210,
    openingTime: '11:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Student ID Bowling Discount (Mon–Thu)', 'Free Shoe Rental'],
    distanceKm: 1.1,
  },
  {
    id: 'p-18',
    name: 'Smaaash Gaming – Cricket & VR',
    category: 'entertainment',
    description: 'Immersive gaming zone with cricket simulators, go-karting, VR experiences, and karaoke rooms for groups.',
    address: 'Forum Mall, Hosur Road',
    area: 'Koramangala',
    city: 'Bengaluru',
    latitude: 12.9279,
    longitude: 77.6271,
    priceLevel: 3,
    approxCostForOne: 450,
    rating: 4.3,
    reviewCount: 3400,
    openingTime: '11:00',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['₹300 Student Group Pass (2+ people)', 'Free VR Trial Round'],
    distanceKm: 6.2,
  },
  // ── RESTAURANTS ───────────────────────────────────────────────────────
  {
    id: 'p-7',
    name: 'Meghana Foods – Biryani Heaven',
    category: 'restaurants',
    description: 'Legendary Koramangala biryani joint famous for its smoky pot biryani and affordable chicken fry thali.',
    address: '107, Koramangala 5th Block',
    area: 'Koramangala',
    city: 'Bengaluru',
    latitude: 12.9352,
    longitude: 77.6245,
    priceLevel: 2,
    approxCostForOne: 250,
    rating: 4.7,
    reviewCount: 9200,
    openingTime: '11:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['2-person sharing biryani ₹300', 'Free Raita Refill'],
    distanceKm: 5.8,
  },
  {
    id: 'p-19',
    name: 'Maiya\'s Restaurant – South Indian Soul',
    category: 'restaurants',
    description: 'Beloved South Indian restaurant with set-dosa combos, rava kesari, and a traditional thali that fills you up for ₹130.',
    address: 'Jayanagar 4th Block',
    area: 'Jayanagar',
    city: 'Bengaluru',
    latitude: 12.9258,
    longitude: 77.5858,
    priceLevel: 1,
    approxCostForOne: 130,
    rating: 4.6,
    reviewCount: 5400,
    openingTime: '07:30',
    closingTime: '22:30',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['₹130 Full Lunch Thali', 'Free Buttermilk Refill'],
    distanceKm: 4.3,
  },
  // ── VIEWPOINTS ────────────────────────────────────────────────────────
  {
    id: 'p-8',
    name: 'Nandi Hills Sunrise Trek',
    category: 'viewpoints',
    description: 'Stunning 1,478m hilltop with the best sunrise views from Bengaluru — misty valleys, ancient temples, and cool wind.',
    address: 'Nandi Hills, Chikkaballapur',
    area: 'Nandi Hills',
    city: 'Chikkaballapur',
    latitude: 13.3708,
    longitude: 77.6835,
    priceLevel: 1,
    approxCostForOne: 200,
    rating: 4.8,
    reviewCount: 12400,
    openingTime: '06:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹5 Entry Ticket', '₹200 Shared Cab from Bangalore', 'Best at 6AM'],
    distanceKm: 60,
  },
  {
    id: 'p-20',
    name: 'Lalbagh Lake – Golden Hour Spot',
    category: 'viewpoints',
    description: 'Serene 240-acre botanical garden with a glassy lake that turns gold at sunset. Perfect evening walk with friends.',
    address: 'Lalbagh Road, Mavalli',
    area: 'Mavalli',
    city: 'Bengaluru',
    latitude: 12.9507,
    longitude: 77.5847,
    priceLevel: 0,
    approxCostForOne: 20,
    rating: 4.7,
    reviewCount: 11200,
    openingTime: '06:00',
    closingTime: '19:00',
    imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹20 Entry (Free on Republic/Independence Day)', 'Photography Hotspot'],
    distanceKm: 3.4,
  },
  // ── CULTURAL/TEMPLES ─────────────────────────────────────────────────
  {
    id: 'p-9',
    name: 'ISKCON Temple & Spiritual Garden',
    category: 'cultural_temples',
    description: 'Magnificent golden-domed ISKCON temple with free prasadam, stunning evening aarti, and tranquil garden walks.',
    address: 'Hare Krishna Hill, Chord Road',
    area: 'Rajajinagar',
    city: 'Bengaluru',
    latitude: 13.0107,
    longitude: 77.5546,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.8,
    reviewCount: 15600,
    openingTime: '07:15',
    closingTime: '20:30',
    imageUrl: 'https://images.unsplash.com/photo-1542202229-7d93c33f5d07?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Prasadam Meal', 'Free Entry', 'Evening Aarti 7 PM'],
    distanceKm: 7.1,
  },
  // ── SHOPPING ──────────────────────────────────────────────────────────
  {
    id: 'p-10',
    name: 'Commercial Street Bazaar',
    category: 'shopping',
    description: 'Bengaluru\'s most vibrant street market with 400+ shops selling ethnic wear, gadgets, street food, and custom clothing.',
    address: 'Commercial Street, Shivajinagar',
    area: 'Shivajinagar',
    city: 'Bengaluru',
    latitude: 12.9810,
    longitude: 77.6083,
    priceLevel: 1,
    approxCostForOne: 300,
    rating: 4.5,
    reviewCount: 18200,
    openingTime: '10:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Bulk Bargains at Wholesale Prices', 'Budget Accessories from ₹50'],
    distanceKm: 2.5,
  },
  // ── PHOTO SPOTS ──────────────────────────────────────────────────────
  {
    id: 'p-11',
    name: 'Church Street Graffiti Lane',
    category: 'photo_spots',
    description: 'A colorful 300m graffiti-lined lane with street murals, neon art, and indie art installations — Bengaluru\'s best aesthetic backdrop.',
    address: 'Church Street, Central Bengaluru',
    area: 'Church Street',
    city: 'Bengaluru',
    latitude: 12.9752,
    longitude: 77.6071,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.6,
    reviewCount: 6800,
    openingTime: '00:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free', 'Best at Golden Hour (5–7 PM)', 'Tripod-Friendly Alleys'],
    distanceKm: 1.1,
  },
  // ── WEEKEND TRIPS ─────────────────────────────────────────────────────
  {
    id: 'p-12',
    name: 'Shivanasamudra Waterfalls Day Trip',
    category: 'weekend_trips',
    description: 'Majestic waterfalls 130km from Bengaluru — twin falls of Gaganachukki & Bharachukki cascade through rocky gorges.',
    address: 'Shivanasamudra, Mandya District',
    area: 'Mandya',
    city: 'Karnataka',
    latitude: 12.3280,
    longitude: 77.1674,
    priceLevel: 2,
    approxCostForOne: 500,
    rating: 4.7,
    reviewCount: 9800,
    openingTime: '08:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1536147116438-62986a88dcbc?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹500 Total per Head via Shared Cab', '₹40 Coracle Ride', 'Monsoon Magic Aug–Oct'],
    distanceKm: 130,
  },
  {
    id: 'p-21',
    name: 'Skandagiri Night Trek',
    category: 'weekend_trips',
    description: 'Famous night trek to misty peak 70km from Bengaluru. Trekkers start at midnight, reach the summit by 4 AM for sunrise above the clouds.',
    address: 'Kalavara Durga, Chikkaballapur',
    area: 'Chikkaballapur',
    city: 'Karnataka',
    latitude: 13.4218,
    longitude: 77.7023,
    priceLevel: 2,
    approxCostForOne: 600,
    rating: 4.9,
    reviewCount: 14200,
    openingTime: '00:00',
    closingTime: '10:00',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹600 Includes Guide + Permit', 'Group Shared Cab Bookings', 'Bucket-list Experience'],
    distanceKm: 70,
  },
  {
    id: 'atp-cult-1',
    name: 'Lepakshi Temple & Monolithic Nandi',
    category: 'cultural_temples',
    description: 'Iconic 16th-century Vijayanagara architectural wonder near Gorantla featuring the world-famous Hanging Pillar, monolithic granite Nandi, and rock carvings.',
    address: 'Lepakshi Heritage Precinct, Near Gorantla',
    area: 'Lepakshi (Near Gorantla)',
    city: 'Anantapur',
    latitude: 13.8042,
    longitude: 77.6083,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 16400,
    openingTime: '06:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry with College ID', 'Spectacular Architecture Photos', 'Popular Student Bike Trip'],
    distanceKm: 25,
  },
  {
    id: 'atp-cult-2',
    name: 'Gorantla Madhava Raya Temple',
    category: 'cultural_temples',
    description: 'Historic Vijayanagara-era temple located right in Gorantla town with carved pillars, spacious stone mandapams, and a peaceful ambiance for study breaks.',
    address: 'Temple Street, Gorantla',
    area: 'Gorantla Town',
    city: 'Anantapur',
    latitude: 13.985,
    longitude: 77.772,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.7,
    reviewCount: 3800,
    openingTime: '06:30',
    closingTime: '19:30',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free Entry', 'Quiet Reading Corners', 'Heritage Stone Courtyard'],
    distanceKm: 0.5,
  },
  {
    id: 'atp-cafe-1',
    name: 'JNTU Campus Hub & Student Chai Adda',
    category: 'cafes',
    description: 'Bustling student hangout zone near JNTU college campus serving hot filter coffee, Osmania biscuits, samosas, and evening study discussions.',
    address: 'Near JNTU College Gate, Anantapur Road',
    area: 'JNTU Campus Hub',
    city: 'Anantapur',
    latitude: 14.651,
    longitude: 77.61,
    priceLevel: 1,
    approxCostForOne: 60,
    rating: 4.6,
    reviewCount: 5200,
    openingTime: '07:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['₹15 Filter Coffee', 'Charging Sockets Available', 'Student Group Discounts'],
    distanceKm: 2.1,
  },
  {
    id: 'atp-food-1',
    name: 'Anantapur Clock Tower Uggani Bajji Street',
    category: 'street_food',
    description: 'The ultimate Rayalaseema comfort food hub! Famous hot crispy mirchi bajjis served with spicy lemon puffed rice (Uggani) and badam milk for under ₹50.',
    address: 'Subhash Road, Clock Tower Circle',
    area: 'Clock Tower',
    city: 'Anantapur',
    latitude: 14.6819,
    longitude: 77.6006,
    priceLevel: 1,
    approxCostForOne: 50,
    rating: 4.8,
    reviewCount: 11200,
    openingTime: '07:30',
    closingTime: '22:30',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Full Breakfast / Evening Snack Under ₹50', 'Legendary Rayalaseema Flavor'],
    distanceKm: 3.4,
  },
  {
    id: 'atp-view-1',
    name: 'Puttaparthi Hills & Chitravathi Riverbank',
    category: 'viewpoints',
    description: 'Serene riverside and hilltop lookout 30 minutes from Gorantla. Cool breezes, tamarind trees, and panoramic sunset viewpoints for college friend road trips.',
    address: 'Chitravathi Road, Puttaparthi',
    area: 'Puttaparthi (Near Gorantla)',
    city: 'Anantapur',
    latitude: 14.168,
    longitude: 77.81,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.7,
    reviewCount: 7900,
    openingTime: '06:00',
    closingTime: '19:00',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Scenic Sunset Photos', 'River Breeze Hangout'],
    distanceKm: 22,
  },
];

// Deduplicate and combine base places with Pan-India places
const basePlaceIds = new Set(BASE_PLACES.map((p) => p.id));
export const INITIAL_FEATURED_PLACES: Place[] = [
  ...BASE_PLACES,
  ...PAN_INDIA_PLACES.filter((p) => !basePlaceIds.has(p.id)),
];

export const POPULAR_SEARCH_QUERIES = [
  'Munnar tea hills Kerala',
  'Araku valley coffee gardens',
  'Hampi ruins Karnataka',
  'Goa beach shacks under ₹200',
  'Jaipur Hawa Mahal rooftop cafes',
  'Rishikesh river rafting',
  'Manali snow spots & cafes',
  'Varanasi evening Ganga aarti',
  'Gorantla & Anantapur hotspots',
  'Cheap food near me',
  'Places under ₹500',
  'Pangong Lake Ladakh',
];
