import type { Place } from '../types';

export const ALL_INDIA_TEMPLES: Place[] = [
  // ─── ANDHRA PRADESH & RAYALASEEMA TEMPLES ─────────────────────────────────
  {
    id: 'ap-tirupati-balaji',
    name: 'Sri Venkateswara Swamy Temple (Tirumala Balaji)',
    category: 'cultural_temples',
    description: 'World-renowned sacred hilltop temple in the Seshachalam Hills. Historic Dravidian gold-plated Ananda Nilayam vimana, iconic laddu prasadam, and scenic trekking footpaths (Alipiri & Srivari Mettu) popular with students.',
    address: 'S Venkata Ramana Temple Rd, Tirumala',
    area: 'Tirumala Hills',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    latitude: 13.6833,
    longitude: 79.3472,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 95000,
    openingTime: '03:00',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Sarva Darshan Access', 'Tirumala Laddu Prasadam', 'Alipiri Footpath 3,550 Steps Trek'],
    distanceKm: 180
  },
  {
    id: 'ap-tirupati-kapila',
    name: 'Kapila Theertham Waterfalls & Shiva Temple',
    category: 'cultural_temples',
    description: 'Ancient Shiva temple nestled right at the base of the Tirumala hills where a roaring mountain waterfall plunges into a sacred stone tank. Peaceful vibes and lush rocky scenery for student visits.',
    address: 'KT Road, Kapila Theertham',
    area: 'Alipiri Foothills',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    latitude: 13.6558,
    longitude: 79.4262,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.8,
    reviewCount: 28000,
    openingTime: '05:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free Entry', 'Natural Mountain Waterfall Views', 'Direct City Bus Connectivity'],
    distanceKm: 185
  },
  {
    id: 'ap-srisailam-mallikarjuna',
    name: 'Sri Bhramaramba Mallikarjuna Swamy Jyotirlinga Temple',
    category: 'cultural_temples',
    description: 'One of the most sacred pilgrimage sites in India housing both a Shiva Jyotirlinga and a Shakti Peeth. Set amidst the deep gorges and tiger reserve forests of the Nallamala Hills overlooking the Krishna River.',
    address: 'Srisailam Devasthanam, Nandyal District',
    area: 'Nallamala Hills',
    city: 'Srisailam',
    state: 'Andhra Pradesh',
    latitude: 16.0741,
    longitude: 78.8687,
    priceLevel: 0,
    approxCostForOne: 60,
    rating: 4.8,
    reviewCount: 42000,
    openingTime: '04:30',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free General Darshan', 'Srisailam Dam Ghat Road Scenic Drive', 'Patalaganga Ropeway Access'],
    distanceKm: 260
  },
  {
    id: 'ap-ahobilam-narasimha',
    name: 'Ahobilam Nava Narasimha Swamy Sacred Cave Temples',
    category: 'cultural_temples',
    description: 'Renowned 9 Narasimha cave temples distributed through dense Nallamala forest hills. Incredible adventure trekking route across Bhavanashini river streams and natural limestone caverns.',
    address: 'Ahobilam, Allagadda Mandal',
    area: 'Upper & Lower Ahobilam',
    city: 'Nandyal',
    state: 'Andhra Pradesh',
    latitude: 15.1322,
    longitude: 78.7188,
    priceLevel: 0,
    approxCostForOne: 80,
    rating: 4.9,
    reviewCount: 19500,
    openingTime: '06:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Ugra Stambham Mountain Ridge Trek', 'Fresh Water Mountain Springs'],
    distanceKm: 170
  },
  {
    id: 'ap-kadiri-narasimha',
    name: 'Kadiri Sri Lakshmi Narasimha Swamy Temple',
    category: 'cultural_temples',
    description: 'Historic Rayalaseema pilgrimage landmark close to Gorantla. Exquisite Vijayanagara pillared corridors, towering Raja Gopuram, and huge festival chariot (Theru) that students visit during weekend road trips.',
    address: 'Temple St, Kadiri Town',
    area: 'Kadiri (Near Gorantla)',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    latitude: 14.1147,
    longitude: 78.1627,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.8,
    reviewCount: 21000,
    openingTime: '06:00',
    closingTime: '20:30',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Darshan', 'Close to Gorantla & Puttaparthi (45 min drive)', 'Authentic Rayalaseema Prasadam'],
    distanceKm: 42
  },
  {
    id: 'ap-penukonda-temple',
    name: 'Penukonda Fort & Sri Kasi Visweswara Temple',
    category: 'cultural_temples',
    description: 'Ancient hill fort capital of the Vijayanagara Empire located minutes from Gorantla. Features mountain watchtowers, Gagan Mahal palace, and sacred historic temples at the scenic hilltop ridge.',
    address: 'Penukonda Hill Fort Road',
    area: 'Penukonda (Near Gorantla)',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    latitude: 14.0833,
    longitude: 77.6000,
    priceLevel: 0,
    approxCostForOne: 20,
    rating: 4.7,
    reviewCount: 14000,
    openingTime: '06:00',
    closingTime: '18:30',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry with College ID', 'Spectacular Sunrise Horizon Trek', 'Very Close to Gorantla (20 km)'],
    distanceKm: 22
  },
  {
    id: 'ap-yaganti-temple',
    name: 'Yaganti Sri Uma Maheshwara Temple & Growing Nandi',
    category: 'cultural_temples',
    description: 'Mystical 15th-century temple set against towering red sandstone cliffs. Famous for the monolithic Nandi idol that constantly expands in size, Pushkarini perennial spring, and saint Agastya cave.',
    address: 'Yaganti, Banaganapalle Mandal',
    area: 'Banaganapalle',
    city: 'Kurnool',
    state: 'Andhra Pradesh',
    latitude: 15.3475,
    longitude: 78.1364,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 31000,
    openingTime: '06:00',
    closingTime: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Perennial Mountain Spring Bathing Tank', 'Venkateswara & Agastya Cave Treks'],
    distanceKm: 140
  },
  {
    id: 'ap-mahanandi-temple',
    name: 'Mahanandi Temple & Natural Mineral Springs',
    category: 'cultural_temples',
    description: 'Enchanting temple bordered by lush mango orchards and emerald paddy fields. The temple tank contains crystal-clear mountain water where you can clearly see a coin at the bottom.',
    address: 'Mahanandi, Thimmapuram',
    area: 'Nallamala Foothills',
    city: 'Nandyal',
    state: 'Andhra Pradesh',
    latitude: 15.4839,
    longitude: 78.6186,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.8,
    reviewCount: 24000,
    openingTime: '05:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Fresh Spring Pool Bathing', 'Free Entry', 'Cool Nallamala Forest Breeze'],
    distanceKm: 165
  },
  {
    id: 'ap-vijayawada-kanakadurgam',
    name: 'Sri Durga Malleswara Swamy (Kanaka Durga) Temple',
    category: 'cultural_temples',
    description: 'Splendid ancient temple perched high on Indrakeeladri Hill over the flowing Krishna River and Prakasam Barrage. Beautiful ghat road views and evening illumination over Vijayawada.',
    address: 'Indrakeeladri Hill, Mallikarjunapeta',
    area: 'Indrakeeladri Hill',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    latitude: 16.5161,
    longitude: 80.6074,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.8,
    reviewCount: 58000,
    openingTime: '04:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free General Darshan', 'Riverfront Promenade Walk', 'Ropeway & Ghat Road Vista'],
    distanceKm: 340
  },
  {
    id: 'ap-vizag-simhachalam',
    name: 'Simhachalam Sri Varaha Lakshmi Narasimha Temple',
    category: 'cultural_temples',
    description: 'Iconic 11th-century hill shrine covered in sandalwood paste (Chandanotsavam). Features ornate Kalinga and Chola architectural stone carvings overlooking the Visakhapatnam hills and sea.',
    address: 'Simhachalam Hill, Near Gopalapatnam',
    area: 'Simhachalam Hill',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    latitude: 17.7667,
    longitude: 83.2500,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 46000,
    openingTime: '06:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Scenic Hill Trek Path (1,000 steps)', 'Free Darshan', 'Direct RTC Buses from Vizag Station'],
    distanceKm: 510
  },

  // ─── SOUTH INDIA ICONIC TEMPLES ──────────────────────────────────────────
  {
    id: 'tn-madurai-meenakshi',
    name: 'Madurai Meenakshi Sundareswarar Amman Temple',
    category: 'cultural_temples',
    description: 'World-famous 2,500-year-old architectural masterpiece with 14 colorful towering gopurams, the Hall of Thousand Pillars, musical stone columns, and golden lotus tank in heart of Madurai.',
    address: 'Madurai Main, Near Vaigai River',
    area: 'Central Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    latitude: 9.9195,
    longitude: 78.1193,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 88000,
    openingTime: '05:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free General Darshan', 'Hall of Thousand Pillars Museum ₹50', 'Jigarthanda Cold Drink Street Stalls nearby'],
    distanceKm: 420
  },
  {
    id: 'tn-rameswaram-ramanatha',
    name: 'Ramanathaswamy Temple & 22 Sacred Theerthams',
    category: 'cultural_temples',
    description: 'Magnificent island temple renowned for having the longest pillared corridor in the world (1,212 granite pillars). Located by the Bay of Bengal and Pamban Sea Bridge.',
    address: 'Rameswaram Island, Ramanathapuram District',
    area: 'Rameswaram Coast',
    city: 'Rameswaram',
    state: 'Tamil Nadu',
    latitude: 9.2881,
    longitude: 79.3174,
    priceLevel: 0,
    approxCostForOne: 60,
    rating: 4.8,
    reviewCount: 65000,
    openingTime: '05:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Agni Theertham Seafront Walk', 'Historic 1,200m Pillared Corridor', 'Dhanushkodi Ghost Town Excursion'],
    distanceKm: 530
  },
  {
    id: 'tn-thanjavur-brihadisvara',
    name: 'Brihadeeswara Temple (Thanjavur Big Temple)',
    category: 'cultural_temples',
    description: '1,000-year-old UNESCO World Heritage granite wonder built by Raja Raja Chola I. The world’s first all-granite temple featuring an 80-tonne single stone dome cap and colossal Nandi statue.',
    address: 'Membalam Rd, Balaganapathy Nagar',
    area: 'Thanjavur Fort',
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    latitude: 10.7828,
    longitude: 79.1318,
    priceLevel: 0,
    approxCostForOne: 20,
    rating: 4.9,
    reviewCount: 52000,
    openingTime: '06:00',
    closingTime: '20:30',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Zero Entry Fee', 'Architectural Photo Walk Paradise', 'Spacious Green Lawns for Friends'],
    distanceKm: 390
  },
  {
    id: 'tn-mahabalipuram-shore',
    name: 'Shore Temple & Pancha Rathas UNESCO Heritage',
    category: 'cultural_temples',
    description: '7th-century rock-cut stone temples standing on the shores of the Bay of Bengal in Mamallapuram. Carved monolithic chariots, open-air bas-relief of Arjuna’s Penance, and ocean breeze.',
    address: 'Shore Temple Rd, Mahabalipuram',
    area: 'Coastal Heritage Zone',
    city: 'Mahabalipuram',
    state: 'Tamil Nadu',
    latitude: 12.6167,
    longitude: 80.1983,
    priceLevel: 1,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 47000,
    openingTime: '06:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Student Ticket ₹40 with ID', 'Beachfront Sunset Hangout', 'Seafood Shacks & Surfing'],
    distanceKm: 270
  },
  {
    id: 'ka-hampi-virupaksha',
    name: 'Sri Virupaksha Temple & Stone Chariot',
    category: 'cultural_temples',
    description: 'Active 7th-century sanctuary in the heart of the Hampi UNESCO ruins beside the Tungabhadra River. Features the 50-meter gateway tower, boulder landscapes, and the famous Vittala stone chariot.',
    address: 'Hampi Bazaar, Bellary District',
    area: 'Hampi Heritage Precinct',
    city: 'Hampi',
    state: 'Karnataka',
    latitude: 15.3350,
    longitude: 76.4600,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 59000,
    openingTime: '06:00',
    closingTime: '19:00',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Bicycle Rental ₹150/day across Ruins', 'Coracle Boat Rides on Tungabhadra River', 'Inexpensive Cafe Shacks'],
    distanceKm: 240
  },
  {
    id: 'ka-murudeshwar-shiva',
    name: 'Murudeshwar Shiva Temple & Giant Coastal Statue',
    category: 'cultural_temples',
    description: 'Iconic 123-foot colossal Shiva statue surrounded on three sides by the Arabian Sea. Features a 20-story modern Rajagopuram with a glass lift taking students to the panoramic top viewing gallery.',
    address: 'Bhatkal Taluk, Murudeshwar Beach',
    area: 'Murudeshwar Beachfront',
    city: 'Murudeshwar',
    state: 'Karnataka',
    latitude: 14.0944,
    longitude: 74.4842,
    priceLevel: 0,
    approxCostForOne: 60,
    rating: 4.8,
    reviewCount: 44000,
    openingTime: '06:00',
    closingTime: '20:30',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Lift Ticket to 18th Floor ₹20', 'Scuba Diving at Netrani Island nearby', 'Water Sports on Murudeshwar Beach'],
    distanceKm: 380
  },
  {
    id: 'ka-mysuru-chamundi',
    name: 'Sri Chamundeshwari Temple & Chamundi Hill',
    category: 'cultural_temples',
    description: 'Historic hilltop temple perched 1,000 meters above Mysuru palace city. Iconic 1,008 stone steps pilgrimage climb, 16-foot monolithic black granite Nandi bull, and panoramic sunset viewpoints.',
    address: 'Chamundi Hill Road, Mysuru',
    area: 'Chamundi Hills',
    city: 'Mysuru',
    state: 'Karnataka',
    latitude: 12.2753,
    longitude: 76.6708,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.8,
    reviewCount: 54000,
    openingTime: '07:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['1,008 Stone Steps Morning Fitness Hike', 'Free General Darshan', 'Mysuru City Night Lights Panorama'],
    distanceKm: 190
  },
  {
    id: 'ka-udupi-krishna',
    name: 'Sri Krishna Matha & Temple',
    category: 'cultural_temples',
    description: '13th-century spiritual sanctuary founded by saint Madhvacharya. Unique silver-plated 9-holed window (Kanakana Kindi), daily vegetarian annadanam feast for all visitors, and serene car street.',
    address: 'Car Street, Thenkpete',
    area: 'Temple Square',
    city: 'Udupi',
    state: 'Karnataka',
    latitude: 13.3409,
    longitude: 74.7523,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 4.9,
    reviewCount: 62000,
    openingTime: '05:30',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Delicious Temple Meals (Annaprasada)', 'Close to Malpe Beach & St. Mary’s Island (15 min)', 'Very Student Friendly'],
    distanceKm: 340
  },

  // ─── NORTH & CENTRAL / WESTERN INDIA ICONIC TEMPLES ────────────────────────
  {
    id: 'up-varanasi-kashi',
    name: 'Kashi Vishwanath Temple & Ganga Ghats',
    category: 'cultural_temples',
    description: 'One of the twelve sacred Jyotirlingas located on the western bank of the holy River Ganga. The new grand Kashi Vishwanath Corridor leads directly to Manikarnika and Dashashwamedh Ghats.',
    address: 'Lahori Tola, Varanasi Old City',
    area: 'Ganga Ghats',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    latitude: 25.3109,
    longitude: 83.0107,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 98000,
    openingTime: '03:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry through Ganga Corridor', 'Evening Ganga Maha Aarti Boat View ₹150', 'Famous Banarasi Chaat & Lassi nearby'],
    distanceKm: 1400
  },
  {
    id: 'up-ayodhya-rammandir',
    name: 'Shri Ram Janmabhoomi Mandir',
    category: 'cultural_temples',
    description: 'Magnificent newly consecrated traditional Nagara-style pink Bansi Paharpur sandstone temple complex on the banks of the Saryu River in Ayodhya. Intricate carved stone pillars and serene spiritual courtyards.',
    address: 'Ram Kot, Ayodhya',
    area: 'Ram Janmabhoomi Precinct',
    city: 'Ayodhya',
    state: 'Uttar Pradesh',
    latitude: 26.7922,
    longitude: 82.1998,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.9,
    reviewCount: 110000,
    openingTime: '06:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free Entry & Sugam Darshan', 'Saryu River Evening Light & Sound Show', 'Free Luggage & Locker Facilities'],
    distanceKm: 1520
  },
  {
    id: 'up-vrindavan-bankebihari',
    name: 'Banke Bihari Temple & Prem Mandir',
    category: 'cultural_temples',
    description: 'Devotional heart of Braj Bhoomi. Prem Mandir is built of Italian white Carrara marble with mesmerizing evening multicolor LED illuminations depicting Krishna leelas.',
    address: 'Chatikara Road, Raman Reti',
    area: 'Vrindavan',
    city: 'Mathura',
    state: 'Uttar Pradesh',
    latitude: 27.5714,
    longitude: 77.6719,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.9,
    reviewCount: 82000,
    openingTime: '05:30',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry to Prem Mandir Grounds', 'Evening Musical Fountain & Illumination', 'Famous Mathura Peda & Rabdi'],
    distanceKm: 1680
  },
  {
    id: 'pb-amritsar-goldentemple',
    name: 'Sri Harmandir Sahib (The Golden Temple)',
    category: 'cultural_temples',
    description: 'The preeminent spiritual shrine of Sikhism. Golden marble sanctum surrounded by the sacred Amrit Sarovar lake, operating the world’s largest free community kitchen (Langar) feeding 100,000 people daily.',
    address: 'Golden Temple Rd, Atta Mandi',
    area: 'Heritage Walk Precinct',
    city: 'Amritsar',
    state: 'Punjab',
    latitude: 31.6200,
    longitude: 74.8765,
    priceLevel: 0,
    approxCostForOne: 0,
    rating: 5.0,
    reviewCount: 145000,
    openingTime: '00:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['100% Free 24/7 Langar Meal', 'Open 24 Hours with Golden Night Reflections', 'Wagah Border Ceremony Day Trip'],
    distanceKm: 2200
  },
  {
    id: 'uk-kedarnath-temple',
    name: 'Kedarnath Dham Himalayan Temple',
    category: 'cultural_temples',
    description: 'One of the highest and holiest of the twelve Jyotirlingas, perched at 3,584 meters altitude against the snow-covered Kedarnath mountain peaks and Mandakini River. Bucket-list Himalayan trek for college students.',
    address: 'Kedarnath Dham, Rudraprayag District',
    area: 'Garhwal Himalayas',
    city: 'Kedarnath',
    state: 'Uttarakhand',
    latitude: 30.7352,
    longitude: 79.0669,
    priceLevel: 0,
    approxCostForOne: 150,
    rating: 4.9,
    reviewCount: 76000,
    openingTime: '04:00',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Breathtaking 16 km Mountain Trek from Gaurikund', 'Budget GMVN Dormitory Stays', 'Snowy Alpine Panoramas'],
    distanceKm: 2150
  },
  {
    id: 'uk-badrinath-temple',
    name: 'Badrinath Temple & Neelkanth Peak',
    category: 'cultural_temples',
    description: 'Sacred Char Dham shrine situated in the Chamoli district between the Nar and Narayana mountain ranges, with the pyramidal peak of Neelkanth in the background along the roaring Alaknanda River.',
    address: 'Badrinath, Chamoli District',
    area: 'Alaknanda Valley',
    city: 'Badrinath',
    state: 'Uttarakhand',
    latitude: 30.7433,
    longitude: 79.4938,
    priceLevel: 0,
    approxCostForOne: 100,
    rating: 4.9,
    reviewCount: 68000,
    openingTime: '04:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Natural Hot Sulphur Springs (Tapt Kund)', 'Mana Village (First Indian Village) 3 km away', 'Vasudhara Waterfalls Trek'],
    distanceKm: 2200
  },
  {
    id: 'gj-somnath-temple',
    name: 'Somnath Jyotirlinga Temple by Arabian Sea',
    category: 'cultural_temples',
    description: 'The first of the twelve sacred Aadi Jyotirlinga shrines located right where the Arabian Sea waves crash against the temple walls. Majestic Chalukya-style stone architecture and sound & light show.',
    address: 'Somnath Beach Rd, Prabhas Patan',
    area: 'Somnath Coast',
    city: 'Somnath',
    state: 'Gujarat',
    latitude: 20.8880,
    longitude: 70.4013,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 84000,
    openingTime: '06:00',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry', 'Evening Sound & Light Show ₹30', 'Sunset Walk along Arabian Sea Promenade'],
    distanceKm: 1250
  },
  {
    id: 'or-puri-jagannath',
    name: 'Shree Jagannath Temple & Grand Road',
    category: 'cultural_temples',
    description: 'Monumental 12th-century temple dedicated to Lord Jagannath, Balabhadra, and Subhadra. World-famous for the annual Ratha Yatra festival, the mysterious non-flying flag, and Asia’s largest kitchen preparing Mahaprasad.',
    address: 'Grand Road, Puri Beach Area',
    area: 'Bada Danda (Grand Road)',
    city: 'Puri',
    state: 'Odisha',
    latitude: 19.8047,
    longitude: 85.8180,
    priceLevel: 0,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 92000,
    openingTime: '05:30',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Delicious Ananda Bazar Mahaprasad under ₹80', 'Puri Golden Beach Walk', 'Konark Sun Temple 35 km away'],
    distanceKm: 1100
  },
  {
    id: 'or-konark-suntemple',
    name: 'Konark Sun Temple & Stone Chariot Wheels',
    category: 'cultural_temples',
    description: '13th-century UNESCO World Heritage architectural marvel designed in the shape of a colossal chariot with 24 carved stone wheels pulled by seven galloping horses on Chandrabhaga beach.',
    address: 'Konark, Puri District',
    area: 'Konark Coastal Heritage',
    city: 'Konark',
    state: 'Odisha',
    latitude: 19.8876,
    longitude: 86.0945,
    priceLevel: 1,
    approxCostForOne: 40,
    rating: 4.8,
    reviewCount: 56000,
    openingTime: '06:00',
    closingTime: '20:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Student Ticket ₹40', 'Chandrabhaga Beach Sunset & Surfing', 'World Famous Intricate Stone Carvings'],
    distanceKm: 1130
  },
  {
    id: 'mp-ujjain-mahakaleshwar',
    name: 'Mahakaleshwar Jyotirlinga & Mahakal Lok',
    category: 'cultural_temples',
    description: 'One of the most powerful Shiva Jyotirlingas in India on the banks of Shipra River. Famous for the sacred dawn Bhasma Aarti and the 900-meter Mahakal Lok corridor lined with 108 grand stone pillars.',
    address: 'Jaisinghpura, Ujjain',
    area: 'Shipra Riverfront',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    latitude: 23.1827,
    longitude: 75.7682,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.9,
    reviewCount: 89000,
    openingTime: '04:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Entry to Grand Mahakal Lok Corridor', 'Ram Ghat Evening Aarti on Shipra', 'Inexpensive Student Street Food'],
    distanceKm: 1150
  },
  {
    id: 'mh-ellora-kailasa',
    name: 'Kailasa Rock-Cut Temple (Cave 16)',
    category: 'cultural_temples',
    description: 'The largest monolithic rock excavation in the world! Chiseled vertically from top to bottom out of a single volcanic basalt cliff face by Rashtrakuta kings. Astounding engineering and spiritual wonder.',
    address: 'Ellora Caves, Aurangabad District',
    area: 'Ellora Caves',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    latitude: 20.0242,
    longitude: 75.1788,
    priceLevel: 1,
    approxCostForOne: 40,
    rating: 4.9,
    reviewCount: 61000,
    openingTime: '06:00',
    closingTime: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Student Entry ₹40', 'Over 34 Caves to Explore with Friends', 'Grishneshwar Jyotirlinga Temple 1 km away'],
    distanceKm: 780
  },
  {
    id: 'as-guwahati-kamakhya',
    name: 'Kamakhya Temple & Nilachal Hill',
    category: 'cultural_temples',
    description: 'Ancient tantric Shakti Peeth perched atop Nilachal Hill overlooking the majestic Brahmaputra River. Mesmerizing beehive-shaped dome architecture and spiritual panoramic viewpoints over Guwahati.',
    address: 'Kamakhya, Nilachal Hill',
    area: 'Nilachal Hill',
    city: 'Guwahati',
    state: 'Assam',
    latitude: 26.1664,
    longitude: 91.7056,
    priceLevel: 0,
    approxCostForOne: 30,
    rating: 4.8,
    reviewCount: 48000,
    openingTime: '05:30',
    closingTime: '21:00',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free General Entry', 'Brahmaputra River Ropeway Ride nearby', 'Scenic Hilltop View over Assam'],
    distanceKm: 2300
  },
  {
    id: 'jk-katra-vaishnodevi',
    name: 'Shri Mata Vaishno Devi Shrine & Holy Cave',
    category: 'cultural_temples',
    description: 'Renowned holy cave shrine situated in the Trikuta Mountains at an altitude of 5,200 feet. The scenic 12 km illuminated mountain track from Katra is a milestone spiritual trek for student groups.',
    address: 'Bhavan, Trikuta Hills',
    area: 'Trikuta Mountain Range',
    city: 'Katra',
    state: 'Jammu and Kashmir',
    latitude: 33.0308,
    longitude: 74.9490,
    priceLevel: 0,
    approxCostForOne: 80,
    rating: 4.9,
    reviewCount: 91000,
    openingTime: '00:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['Free Yatra Registration', 'Illuminated Night Mountain Trek with Friends', 'Bhairon Ghati Ropeway ₹100'],
    distanceKm: 2450
  }
];
