import type { Place } from '../types';

export const ALL_THEATRES_STAGE_PLACES: Place[] = [
  // ─── CHENNAI THEATRES & STAGE ─────────────────────────────────────────────
  {
    id: 'chn-th-sathyam-1',
    name: 'Sathyam Cinemas (SPI Cinemas / PVR)',
    category: 'theatres',
    description: 'The undisputed holy grail of cinema for Chennai college students. Famous for its world-renowned seasoning butter popcorn, Dolby Atmos sound, crystal clear projection, and electric movie premiere atmosphere.',
    address: '8 Thiruvika Road, Royapettah',
    area: 'Royapettah',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0583,
    longitude: 80.2618,
    priceLevel: 1,
    approxCostForOne: 190,
    rating: 4.9,
    reviewCount: 54000,
    openingTime: '08:30',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['World-Famous Butter Popcorn with Seasonings', 'Student Matinee Shows Under ₹150', 'Dolby Atmos Sound'],
    distanceKm: 3.5
  },
  {
    id: 'chn-th-rohini-1',
    name: 'Rohini Silver Screens (Fans Fort)',
    category: 'theatres',
    description: 'Known as the "Fans Fort" of Kollywood! The epicenter of 4 AM First Day First Show (FDFS) celebrations, massive cutout banners, milk abhishekam, and roaring student crowd celebrations in Koyambedu.',
    address: 'Poonamallee High Road, Koyambedu',
    area: 'Koyambedu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0722,
    longitude: 80.1942,
    priceLevel: 1,
    approxCostForOne: 160,
    rating: 4.8,
    reviewCount: 38000,
    openingTime: '07:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Legendary 4 AM FDFS Celebrations', 'RGB Laser Screens', 'Pocket-Friendly Snacks & Popcorn'],
    distanceKm: 8.5
  },
  {
    id: 'chn-th-vettri-1',
    name: 'Vettri Theatres RGB 4K Laser, Chromepet',
    category: 'theatres',
    description: 'A legendary suburban cinema transformed into a cutting-edge RGB 4K laser multiplex. The top movie hangout for engineering students from MIT, SRM, and B.S. Abdur Rahman Crescent universities.',
    address: 'Grand Southern Trunk Road, Chromepet',
    area: 'Chromepet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.9516,
    longitude: 80.1415,
    priceLevel: 1,
    approxCostForOne: 140,
    rating: 4.8,
    reviewCount: 32000,
    openingTime: '09:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['RGB 4K Laser Projection', 'Earth-Shaking Subwoofer Sound System', 'Budget Tickets under ₹150'],
    distanceKm: 18.0
  },
  {
    id: 'chn-th-udhayam-1',
    name: 'Udhayam Theatres Complex, Ashok Nagar',
    category: 'theatres',
    description: 'A 40-year-old historic landmark complex with 4 iconic screens (Udhayam, Mini Udhayam, Suriyan, Chandiran). Unbeatable value for college students with tickets starting at just ₹120.',
    address: '1 100 Feet Road, Ashok Nagar',
    area: 'Ashok Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0337,
    longitude: 80.2114,
    priceLevel: 0,
    approxCostForOne: 120,
    rating: 4.6,
    reviewCount: 29000,
    openingTime: '09:30',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Tickets Starting at ₹120', 'Adjacent to Ashok Nagar Metro Station', 'Classic Vintage Chennai Vibe'],
    distanceKm: 7.2
  },
  {
    id: 'chn-th-devi-1',
    name: 'Devi Cineplex (Devi Paradise 70mm), Mount Road',
    category: 'theatres',
    description: 'Iconic curved-screen 70mm palace theater situated right on Anna Salai. Giant 1,000-seat auditorium, thumping audio, and an all-time favorite single-screen pilgrimage for student groups.',
    address: '48 Anna Salai, Border Thottam',
    area: 'Anna Salai / Mount Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0645,
    longitude: 80.2678,
    priceLevel: 1,
    approxCostForOne: 150,
    rating: 4.7,
    reviewCount: 27000,
    openingTime: '10:00',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Massive 70mm Giant Curved Screen', 'Classic Mount Road City Center Landmark', 'Budget Samosas & Tea'],
    distanceKm: 2.9
  },
  {
    id: 'chn-th-kasi-1',
    name: 'Kasi Theatre, Jafferkhanpet',
    category: 'theatres',
    description: 'One of the most high-voltage single-screen movie venues in South India. Known for electrifying whistle culture, student cheer groups, giant screen clarity, and budget ticket pricing.',
    address: 'Pillaiyar Koil Street, Jafferkhanpet',
    area: 'Jafferkhanpet / Ashok Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0232,
    longitude: 80.2033,
    priceLevel: 0,
    approxCostForOne: 120,
    rating: 4.6,
    reviewCount: 21000,
    openingTime: '10:00',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['High Energy Crowd Atmosphere', 'Cheapest Snack Menu in City', 'Student Fan Celebrations'],
    distanceKm: 8.0
  },
  {
    id: 'chn-th-palazzo-1',
    name: 'PVR Palazzo IMAX, Nexus Vijaya Mall',
    category: 'theatres',
    description: 'An Italian Renaissance-inspired palace multiplex complete with neoclassical marble statues, frescoes, and a massive IMAX auditorium. Direct connectivity via Vadapalani Metro station.',
    address: 'Nexus Vijaya Mall, Arcot Road, Vadapalani',
    area: 'Vadapalani',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0504,
    longitude: 80.2097,
    priceLevel: 2,
    approxCostForOne: 230,
    rating: 4.8,
    reviewCount: 31000,
    openingTime: '09:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Direct Vadapalani Metro Skywalk', 'IMAX Laser Experience', 'Italian Palace Themed Interiors'],
    distanceKm: 7.0
  },
  {
    id: 'chn-th-mayajaal-1',
    name: 'Mayajaal Multiplex & Resort, ECR',
    category: 'theatres',
    description: 'India\'s largest multiplex complex with 16 screens, bowling alleys, beach video arcade, and swimming pool. The quintessential weekend coastal road drive destination for college gangs.',
    address: 'East Coast Road, Kanathur',
    area: 'ECR Kanathur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 12.8580,
    longitude: 80.2458,
    priceLevel: 1,
    approxCostForOne: 180,
    rating: 4.7,
    reviewCount: 34000,
    openingTime: '09:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['16 Screens - Every Movie Show Available', 'Bowling Alley & Arcade Gaming', 'Coastal ECR Bike Ride Route'],
    distanceKm: 24.0
  },
  {
    id: 'chn-th-music-academy-1',
    name: 'The Music Academy & TTK Auditorium Stage',
    category: 'theatres',
    description: 'The landmark cultural stage of South India. Hosts world-class classical Carnatic concerts, Bharatanatyam dance dramas, national theatre festivals, and contemporary college English plays.',
    address: '168 TTK Road, Royapettah',
    area: 'Royapettah / Alwarpet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0445,
    longitude: 80.2580,
    priceLevel: 1,
    approxCostForOne: 100,
    rating: 4.9,
    reviewCount: 18500,
    openingTime: '09:00',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Student Passes for Cultural Theatre & Plays', 'World-Class Acoustics', 'Annual December Madras Music Festival'],
    distanceKm: 4.0
  },
  {
    id: 'chn-th-sir-mutha-1',
    name: 'Sir Mutha Venkatasubba Rao Concert Hall, Chetpet',
    category: 'theatres',
    description: 'A premier air-conditioned acoustic theatre with 1,200 plush seats. Stages Broadway-style musicals, English stage plays, live stand-up comedy specials, and college rock choir fests.',
    address: '7 Shenstone Park, Chetpet',
    area: 'Chetpet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0718,
    longitude: 80.2396,
    priceLevel: 2,
    approxCostForOne: 250,
    rating: 4.8,
    reviewCount: 14200,
    openingTime: '10:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Top Standup Comedy Specials', 'Student Concessions for Theatre Festivals', 'Central Chetpet Location'],
    distanceKm: 4.5
  },

  // ─── BENGALURU THEATRES & STAGE ───────────────────────────────────────────
  {
    id: 'blr-th-urvashi-1',
    name: 'Urvashi Digital 4K RGB Laser Cinema, Lalbagh',
    category: 'theatres',
    description: 'Bengaluru\'s most iconic single-screen movie cathedral. Famous for having South India\'s most thunderous curved screen, Dolby Atmos 64-channel sound, and loyal student crowd.',
    address: '40 Siddaiah Road, Sudhama Nagar',
    area: 'Lalbagh Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9568,
    longitude: 77.5898,
    priceLevel: 1,
    approxCostForOne: 170,
    rating: 4.8,
    reviewCount: 42000,
    openingTime: '09:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Barco 4K RGB Laser Projection', 'Giant Curved Screen', 'Near Lalbagh Metro'],
    distanceKm: 4.2
  },
  {
    id: 'blr-th-ranga-1',
    name: 'Ranga Shankara Theatre & Cafe, JP Nagar',
    category: 'theatres',
    description: 'Bengaluru\'s beloved temple of live theatre founded by Arundhati Nag. Stages a new live play almost every single evening! Famous for ₹100 student tickets, and hot sabudana vadas & ginger tea at the courtyard cafe.',
    address: '36/2 8th Cross Road, JP Nagar 2nd Phase',
    area: 'JP Nagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9128,
    longitude: 77.5855,
    priceLevel: 0,
    approxCostForOne: 120,
    rating: 4.9,
    reviewCount: 22000,
    openingTime: '10:00',
    closingTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Live Plays Starting at ₹100', 'Iconic Courtyard Chai & Sabudana Vada', 'Vibrant Artist & Student Crowd'],
    distanceKm: 7.8
  },

  // ─── HYDERABAD THEATRES & STAGE ───────────────────────────────────────────
  {
    id: 'hyd-th-prasads-1',
    name: 'Prasad\'s Multiplex & PCX Giant Screen, Necklace Road',
    category: 'theatres',
    description: 'Hyderabad\'s premier movie entertainment destination on the banks of Hussain Sagar Lake. Featuring the massive Prasad\'s Big Screen (PCX), 4K projection, gaming zone, and lakefront evening breeze.',
    address: 'NTR Gardens, Necklace Road',
    area: 'Necklace Road',
    city: 'Hyderabad',
    state: 'Telangana',
    latitude: 17.4116,
    longitude: 78.4682,
    priceLevel: 1,
    approxCostForOne: 200,
    rating: 4.8,
    reviewCount: 65000,
    openingTime: '08:30',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: true,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['India\'s Largest PCX Giant Screen', 'Gaming & Laser Tag Zone', 'Lakefront Street Food'],
    distanceKm: 5.5
  },
  {
    id: 'hyd-th-sudarshan-1',
    name: 'Sudarshan 35mm & RTC X Roads Movie Hub',
    category: 'theatres',
    description: 'The Mecca of Tollywood mass cinema! RTC X Roads is globally famous for the most energetic fan celebrations, paper confetti storms, cutouts, and ₹130 tickets for college squads.',
    address: 'Chikkadpally, RTC Cross Roads',
    area: 'RTC X Roads',
    city: 'Hyderabad',
    state: 'Telangana',
    latitude: 17.4042,
    longitude: 78.4975,
    priceLevel: 0,
    approxCostForOne: 130,
    rating: 4.7,
    reviewCount: 38000,
    openingTime: '09:00',
    closingTime: '23:59',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['World-Famous Mass Fan Atmosphere', 'Legendary Bawarchi Biryani Right Opposite', 'Unmatched Bass Sound'],
    distanceKm: 6.2
  },

  // ─── MUMBAI THEATRES & STAGE ──────────────────────────────────────────────
  {
    id: 'mum-th-prithvi-1',
    name: 'Prithvi Theatre & Irish Coffee Cafe, Juhu',
    category: 'theatres',
    description: 'The historic soul of Indian experimental theatre founded by Shashi Kapoor and Jennifer Kendal. Intimate thrust stage hosting legendary actors, poets, and writers. Don\'t miss the famous Irish coffee & cutting chai!',
    address: '20 Janki Kutir, Juhu Church Road',
    area: 'Juhu',
    city: 'Mumbai',
    state: 'Maharashtra',
    latitude: 19.1062,
    longitude: 72.8258,
    priceLevel: 1,
    approxCostForOne: 150,
    rating: 4.9,
    reviewCount: 35000,
    openingTime: '10:00',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    hasWifi: true,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: true,
    isStudentFriendly: true,
    studentPerks: ['World-Famous Irish Coffee & Sulemani Chai', 'Daily Live Theatre Plays from ₹150', 'Juhu Beach 200m away'],
    distanceKm: 8.0
  },
  {
    id: 'mum-th-maratha-1',
    name: 'Maratha Mandir & DDLJ Matinee, Mumbai Central',
    category: 'theatres',
    description: 'A Guinness Record holder for screening Dilwale Dulhania Le Jayenge (DDLJ) every single day for over 28 continuous years! Beautiful Art Deco 1,000-seat balcony with morning tickets at just ₹30–₹50.',
    address: 'Maratha Mandir Marg, Mumbai Central',
    area: 'Mumbai Central',
    city: 'Mumbai',
    state: 'Maharashtra',
    latitude: 18.9696,
    longitude: 72.8193,
    priceLevel: 0,
    approxCostForOne: 50,
    rating: 4.8,
    reviewCount: 31000,
    openingTime: '10:30',
    closingTime: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['11:30 AM DDLJ Matinee for ₹30', 'Historic Bollywood Heritage', 'Opposite Mumbai Central Station'],
    distanceKm: 4.5
  },

  // ─── DELHI THEATRES & STAGE ───────────────────────────────────────────────
  {
    id: 'del-th-kamani-1',
    name: 'Kamani Auditorium & Mandi House Theatre Circuit',
    category: 'theatres',
    description: 'The cultural beating heart of theatre in the capital. Stages classical plays, contemporary Hindi dramas by National School of Drama (NSD) artists, and college theatre fest finals.',
    address: '1 Copernicus Marg, Mandi House',
    area: 'Mandi House',
    city: 'Delhi',
    state: 'Delhi',
    latitude: 28.6234,
    longitude: 77.2346,
    priceLevel: 1,
    approxCostForOne: 120,
    rating: 4.8,
    reviewCount: 22000,
    openingTime: '09:00',
    closingTime: '21:30',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: true,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Special Student Concessions with College ID', 'Mandi House Chai & Bun Makkhan', 'Top NSD Productions'],
    distanceKm: 3.0
  },
  {
    id: 'del-th-delite-1',
    name: 'Delite Cinema & Diamond 4K, Asaf Ali Road',
    category: 'theatres',
    description: 'Historic 1954 heritage art deco cinema near Delhi Gate. Features gold-leaf ceilings, royal brass chandeliers, and the legendary ₹40 samosas and kulfi.',
    address: 'Asaf Ali Road, Delhi Gate',
    area: 'Old Delhi / Delhi Gate',
    city: 'Delhi',
    state: 'Delhi',
    latitude: 28.6415,
    longitude: 77.2405,
    priceLevel: 1,
    approxCostForOne: 150,
    rating: 4.7,
    reviewCount: 28000,
    openingTime: '10:00',
    closingTime: '23:30',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    hasWifi: false,
    hasCharging: false,
    isQuiet: false,
    isOutdoor: false,
    isStudentFriendly: true,
    studentPerks: ['Palatial Vintage Art Deco Interiors', 'Famous Delite Samosa & Rabri Jalebi', 'Student Group Discounts'],
    distanceKm: 4.0
  }
];
